# Generated by Django 2.0.7 on 2018-07-12 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('project_id', models.IntegerField(max_length=20, verbose_name='项目编号')),
                ('province', models.CharField(max_length=255, verbose_name='省份的名字')),
                ('city', models.CharField(max_length=255, verbose_name='城市名字')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(max_length=20, verbose_name='用户所属渠道')),
                ('project_id', models.IntegerField(max_length=20, verbose_name='项目编号')),
                ('room_id', models.IntegerField(max_length=20, verbose_name='房间号')),
                ('bed_num', models.CharField(max_length=255, verbose_name='床号')),
                ('device_no', models.IntegerField(max_length=20, verbose_name='设备编号')),
                ('person_id', models.ImageField(max_length=20, upload_to='', verbose_name='用户ID')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_no', models.IntegerField(max_length=20, verbose_name='设备编号')),
                ('project_id', models.IntegerField(max_length=20, verbose_name='项目编号')),
                ('channel_id', models.IntegerField(max_length=20, verbose_name='渠道编号')),
                ('user_name', models.CharField(max_length=255, verbose_name='用户名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(max_length=20, verbose_name='渠道编号')),
                ('project_id', models.IntegerField(max_length=20, verbose_name='项目编号')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('password', models.CharField(max_length=255, verbose_name='用户密码')),
                ('real_name', models.CharField(max_length=255, verbose_name='用户名称')),
                ('last_login_ip', models.CharField(max_length=255, verbose_name='上次登录IP')),
                ('last_login_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上次登录时间')),
                ('status', models.IntegerField(max_length=1, verbose_name='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
        ),
    ]
