# Generated by Django 2.0.4 on 2018-07-29 03:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rocky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 3, 50, 17, 131746), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 29, 3, 50, 17, 131769), verbose_name='更新时间'),
        ),
    ]
