# Generated by Django 2.0.7 on 2018-08-09 02:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rocky', '0003_auto_20180809_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_item', models.CharField(max_length=255, verbose_name='备忘内容')),
                ('datetime', models.DateTimeField(verbose_name='开始时间')),
                ('schedule', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='计划时长')),
                ('status', models.SmallIntegerField(max_length=255, verbose_name='notice状态：0_未完成，1_已完成')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
        ),
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 10, 41, 32, 468560), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 10, 41, 32, 468560), verbose_name='更新时间'),
        ),
    ]
