# Generated by Django 2.0.4 on 2018-09-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocky', '0006_auto_20180915_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontent',
            name='content',
            field=models.TextField(max_length=50000, verbose_name='章节内容'),
        ),
    ]
