# Generated by Django 2.0.7 on 2018-09-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocky', '0007_auto_20180915_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='introduction',
            field=models.TextField(default='', max_length=1500, verbose_name='内容简介'),
        ),
    ]
