# Generated by Django 2.0.4 on 2018-10-03 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rocky', '0009_notice_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End_time'),
        ),
    ]
