# Generated by Django 2.0.4 on 2018-10-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocky', '0010_auto_20181003_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='end_time',
        ),
    ]
