# Generated by Django 2.0.4 on 2018-10-06 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rocky', '0011_remove_notice_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='备忘内容')),
                ('author', models.CharField(max_length=255, verbose_name='备忘内容')),
                ('content', models.TextField(max_length=50000, verbose_name='章节内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='PoetryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=255, verbose_name='注释内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('poetry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poetry_comments', to='rocky.Poetry')),
            ],
        ),
    ]
