# Generated by Django 2.0.7 on 2018-10-09 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rocky', '0012_poetry_poetrycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcomment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_commener', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diary',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diary_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End_time'),
        ),
        migrations.AddField(
            model_name='notice',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notic_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poetrycomment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='poetry_commener', to=settings.AUTH_USER_MODEL),
        ),
    ]
